name: 'CICD Security Scanner'
description: 'Secret scanning with Gitleaks for PR diffs'
author: 'LauraWangQiu'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  base_ref:
    description: 'Base branch reference'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build scanner image
      shell: bash
      run: docker build -t cicd-security-scanner ${{ github.action_path }}

    - name: Run secret scanning
      shell: bash
      env:
        GITHUB_BASE_REF: ${{ inputs.base_ref }}
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/scan \
          -e GITHUB_BASE_REF=${{ inputs.base_ref }} \
          cicd-security-scanner

    - name: Check if secrets were found
      id: check_secrets
      shell: bash
      run: |
        if [ -f results.sarif ]; then
          COUNT=$(jq '.runs[0].results | length' results.sarif 2>/dev/null || echo 0)
          if [ "$COUNT" -gt 0 ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        echo "found=false" >> $GITHUB_OUTPUT

    - name: Upload SARIF artifact
      if: steps.check_secrets.outputs.found == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: results.sarif

    - name: Comment secrets inline on PR
      if: steps.check_secrets.outputs.found == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const script = require('${{ github.action_path }}/scripts/comment-secrets.js');
          await script({ github, context });

    - name: Fail if secrets found
      if: steps.check_secrets.outputs.found == 'true'
      shell: bash
      run: exit 1