name: 'CICD Security Scanner'
description: 'Secret scanning with Gitleaks for PR diffs'
author: 'LauraWangQiu'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  base_ref:
    description: 'Base branch reference'
    required: false
    default: 'main'

runs:
  using: 'node20'
  main: 'index.js'