name: 'CICD Security Scanner'
description: 'Secret scanning with Gitleaks for PR diffs'
author: 'LauraWangQiu'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  base_ref:
    description: 'Base branch reference'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Build scanner image
      shell: bash
      run: docker build -t cicd-security-scanner ${{ github.action_path }}

    - name: Run secret scanning
      shell: bash
      env:
        GITHUB_BASE_REF: ${{ inputs.base_ref }}
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/scan \
          -e GITHUB_BASE_REF=${{ inputs.base_ref }} \
          cicd-security-scanner

    - name: Check if secrets were found
      id: check_secrets
      shell: bash
      run: |
        if [ -f results.sarif ]; then
          COUNT=$(jq '.runs[0].results | length' results.sarif 2>/dev/null || echo 0)
          if [ "$COUNT" -gt 0 ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        echo "found=false" >> $GITHUB_OUTPUT

    - name: Upload SARIF artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: results.sarif

    - name: Comment secrets inline on PR
      if: steps.check_secrets.outputs.found == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          const sarif = JSON.parse(fs.readFileSync('results.sarif', 'utf8'));
          const results = sarif.runs?.[0]?.results || [];

          if (results.length === 0) {
            console.log("No results to comment.");
            return;
          }

          for (const r of results) {
            const loc = r.locations?.[0]?.physicalLocation;
            if (!loc) continue;

            const path = loc.artifactLocation.uri;
            const line = loc.region.startLine;

            const rule = r.ruleId || "Secret detected";
            const message = r.message?.text || "Potential secret found";

            try {
              await github.rest.pulls.createReviewComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                path: path,
                line: line,
                side: "RIGHT",
                body: `🔐 **Secret detected by Gitleaks**\n\n**Rule:** ${rule}\n**Details:** ${message}\n\n❌ Remove this secret and rotate it immediately.`
              });

              console.log(`Commented on ${path}:${line}`);
            } catch (e) {
              console.log(`Failed to comment on ${path}:${line}`, e.message);
            }
          }

    - name: Fail if secrets found
      if: steps.check_secrets.outputs.found == 'true'
      shell: bash
      run: exit 1