name: Secret scanning

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # MUY IMPORTANTE para gitleaks

      - name: Build scanner image
        run: docker build -t cicd-security-scanner .

      - name: Run secret scanning
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/scan \
            cicd-security-scanner

      - name: Prepare artifact contents
        if: always()
        run: |
          mkdir -p artifact
          cp reports/gitleaks.json artifact/gitleaks.json
          {
            echo "repository=${{ github.repository }}"
            echo "commit_sha=${{ github.sha }}"
            echo "commit_url=https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          } > artifact/metadata.txt

      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.sha }}
          path: artifact